# Generated by Django 2.2 on 2020-05-30 04:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'verbose_name': 'appointment', 'verbose_name_plural': 'appointments'},
        ),
        migrations.AlterModelOptions(
            name='pediatrician',
            options={'verbose_name': 'pediatrician', 'verbose_name_plural': 'pediatricians'},
        ),
        migrations.AddField(
            model_name='pediatrician',
            name='email',
            field=models.EmailField(default='dummy@fake.com', max_length=254, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='commentary',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='commentary'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='datetime',
            field=models.DateTimeField(verbose_name='datetime'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='pediatrician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='api.Pediatrician', verbose_name='pediatrician'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='pediatrician',
            name='name',
            field=models.CharField(max_length=64, verbose_name='name'),
        ),
    ]
