# Generated by Django 2.2 on 2020-05-30 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200529_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pediatrician',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email'),
        ),
    ]
